### ISSUE TITLE
TypeError: query.select.split is not a function

### ISSUE THREAD

**Issue by jugglingthebits** [contentful/contentful.js#503]
My team is seeing failures in the Contentful client since the update from 7.14.13 to 7.15.2.

## Actual Behavior

We're having numerous tests fail with the following error:

```
TypeError: query.select.split is not a function
      at normalizeSelect (node_modules/contentful/dist/webpack:/contentful/utils/normalize-select.js:14:35)
      at Object.getEntries (node_modules/contentful/dist/webpack:/contentful/create-contentful-api.js:216:20)
      at getCachedContentfulEntriesOrFetch (src/clients/contentful/contentful-client.ts:616:44)`
```

FYI Updating to 8.0.3 exhibits the same error
```
TypeError: query.select.split is not a function
    at normalizeSelect (/home/circleci/alma/api/node_modules/contentful/dist/webpack:/contentful/utils/normalize-select.js:14:35)
    at Object.getEntries (/home/circleci/alma/api/node_modules/contentful/dist/webpack:/contentful/create-contentful-api.js:227:20)
    at getCachedContentfulEntriesOrFetch (/home/circleci/alma/api/src/clients/contentful/contentful-client.ts:616:44)
```

## Context

The client is breaking production code.

## Environment

-   **Language Version**: 12.20.0
-   **Operating System**: Docker image `cimg/node:12.20.0`
-   **Package Version**: 7.15.2
-   **Which API are you using?**: Delivery

**Comment by TimBeyer** [comment]
Could you share what you are passing as `query.select`?
We [fixed a bug with the select behavior in 7.15.1](https://github.com/contentful/contentful.js/pull/492) with the existing code indicating that the `select` option will always be a string.  
Of course the querystring serializer might still take an array of strings there, and it seems we simply use the default [`qs.stringify`](https://github.com/contentful/contentful-sdk-core/blob/master/src/create-http-client.ts#L98) behavior there which as a default would be using the array notation like `foo[0]=a&foo[1]=b&foo[2]=c` which isn't supported in the API according to [the docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/select-operator).  
So I'm wondering if you were calling it with an array of strings, and if that actually did show the expected behavior pointing to either a different serializer or the API secretly parsing that kind of syntax as well.

**Comment by jugglingthebits** [comment]
@TimBeyer We observe numerous different queries failing. Here is an example query (passed to `getEntries<T>(query?: any)`:
![grafik](https://user-images.githubusercontent.com/3235163/101332308-64e52500-3875-11eb-8aae-ef251e134432.png)

**Comment by TimBeyer** [comment]
I see you actually passed an array then. Did that actually show the expected behavior?  
According to the official docs that should not actually work.

**Comment by TimBeyer** [comment]
In any case I think this should be a valid way of using the `select` operator since an array makes much more sense than a string with comma separated values, I'm mainly just wondering if the API actually accepted the payloads in a way that was not documented.

**Comment by jugglingthebits** [comment]
>I see you actually passed an array then. Did that actually show the expected behavior?

Since this has been used in our project for a long time, I guess the answer is yes (for versions up to 7.14.13). I cannot tell *why* we're using the api this way though. Maybe it's just what we ended doing when experimenting with the api, since typings just use `any` and I can't see anything in the api docs how to properly do this.
If this api is not supported (and won't be soon), could you share an example how to use `select` properly from the js api?

**Comment by TimBeyer** [comment]
I added your use case to be officially supported so that all those also go through the correct select normalization procedure. The new version should be released in a few minutes.

**Comment by jugglingthebits** [comment]
@TimBeyer thank you for getting this resolved so quickly!
