### ISSUE TITLE
contentful-resolve-response v1.9.1 is broken

### ISSUE THREAD

**Issue by lukehillonline** [contentful/contentful.js#2398]
## Expected Behavior

Contentful works with contentful-resolve-response v1.9.1

## Actual Behavior

Contentful fails with contentful-resolve-response v1.9.1

```
err: {
    "type": "TypeError",
    "message": "resolveResponse is not a function",
    "stack":
        TypeError: resolveResponse is not a function
            at resolveCircular ({local_path}/node_modules/contentful/dist/esm/utils/resolve-circular.js:7:29)
            at internalGetEntries ({local_path}/node_modules/contentful/dist/esm/create-contentful-api.js:165:20)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
            at async getContentfulReactComponentFromQuery (webpack-internal:///./helpers/api/contentfulClient/contentfulClient.ts:64:24)
            at async getServerSideProps$1 (webpack-internal:///./pages/how-to-buy/index.page.tsx:38:21)
            at async {local_path}/node_modules/@sentry/nextjs/cjs/common/utils/wrapperUtils.js:38:14
            at async e8 ({local_path}/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:124)
            at async doRender ({local_path}/node_modules/next/dist/server/base-server.js:1425:30)
            at async cacheEntry.responseCache.get.routeKind ({local_path}/node_modules/next/dist/server/base-server.js:1599:28)
            at async DevServer.renderToResponseWithComponentsImpl ({local_path}/node_modules/next/dist/server/base-server.js:1507:28)
            at async DevServer.renderPageComponent ({local_path}/node_modules/next/dist/server/base-server.js:1931:24)
            at async DevServer.renderToResponseImpl ({local_path}/node_modules/next/dist/server/base-server.js:1969:32)
            at async DevServer.pipeImpl ({local_path}/node_modules/next/dist/server/base-server.js:920:25)
            at async NextNodeServer.handleCatchallRenderRequest ({local_path}/node_modules/next/dist/server/next-server.js:272:17)
            at async DevServer.handleRequestImpl ({local_path}/node_modules/next/dist/server/base-server.js:816:17)
            at async {local_path}/node_modules/next/dist/server/dev/next-dev-server.js:339:20
            at async Span.traceAsyncFn ({local_path}/node_modules/next/dist/trace/trace.js:154:20)
            at async DevServer.handleRequest ({local_path}/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
            at async invokeRender ({local_path}/node_modules/next/dist/server/lib/router-server.js:174:21)
            at async handleRequest ({local_path}/node_modules/next/dist/server/lib/router-server.js:353:24)
            at async requestHandlerImpl ({local_path}/node_modules/next/dist/server/lib/router-server.js:377:13)
            at async Server.requestListener ({local_path}/node_modules/next/dist/server/lib/start-server.js:141:13)
}
```

## Possible Solution

Inside of contentful-resolve-response v1.9.1 PR (see link) it no longer compilies with babel and this could be the issue https://github.com/contentful/contentful-resolve-response/pull/377/files

## Steps to Reproduce

1. Create an app
2. Install contentful (any version) we tested both 11.2.5 and 11.3.0
3. contentful-resolve-response v1.9.1
4. Make a request to get some contentful data

## Context

This completely stops us from being able to fetch contentful data

## Environment

-   **Package Manager Version**: yarn stable
-   **Browser Version**: All
-   **Operating System**: All
-   **Package Version**: 11.2.5 and 11.3.0
-   **Which API are you using?**: Delivery and Preview

**Comment by aholland** [comment]
Workaround: list `"contentful-resolve-response": "1.9.2",` in your package.json

Fix: change `"contentful-resolve-response": "^1.9.0",` to `"contentful-resolve-response": "^1.9.2",` in https://github.com/contentful/contentful.js/blob/f11a7e4d9c1c5db52de0ac066f558131de35bb65/package.json

`1.9.1` is also causing problems under Vite 6, specifically `resolveResponse is not a function`.

**Comment by lukehillonline** [comment]
I can confirm all is working again with 1.9.2, I'll close this now
